#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "httpx>=0.27",
#   "pydantic>=2.7",
#   "rich>=13",
#   "json5>=0.9",
#   "PyYAML>=6",
# ]
# ///
"""
merge_nesting.py — Fetch upstream antfu/vscode-file-nesting-config and merge
personal patterns on top, then render a README.md the VS Code extension can read.

Usage:
  uv run merge_nesting.py [--dry-run] [--patterns personal-patterns.yaml]
"""

import re
import sys
from pathlib import Path
from typing import Annotated

import httpx
import json5
import yaml
from pydantic import BaseModel, Field
from rich.console import Console
from rich.panel import Panel

console = Console(stderr=True)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

UPSTREAM_README_URL = (
    "https://raw.githubusercontent.com/antfu/vscode-file-nesting-config/main/README.md"
)
JSONC_FENCE_PATTERN = re.compile(
    r"```jsonc\n(?P<block>.*?)```", re.DOTALL
)
REPO_NOTE = (
    "<!-- Auto-generated by merge_nesting.py — do not edit README.md directly.\n"
    "     Edit personal-patterns.yaml and re-run, or wait for the scheduled GitHub Action. -->"
)


# ---------------------------------------------------------------------------
# Pydantic models
# ---------------------------------------------------------------------------


class PatternEntry(BaseModel):
    key: str
    patterns: list[str]


class PersonalConfig(BaseModel):
    patterns: list[PatternEntry] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Core logic
# ---------------------------------------------------------------------------


def fetch_upstream_readme() -> str:
    console.log(f"[bold]Fetching[/bold] upstream README from {UPSTREAM_README_URL}")
    resp = httpx.get(UPSTREAM_README_URL, follow_redirects=True, timeout=30)
    resp.raise_for_status()
    return resp.text


def extract_jsonc_block(readme: str) -> str:
    m = JSONC_FENCE_PATTERN.search(readme)
    if not m:
        console.print("[red]ERROR[/red] Could not find ```jsonc block in upstream README.")
        sys.exit(1)
    return m.group("block")


def parse_jsonc_block(raw: str) -> tuple[dict, str]:
    """
    Parse the upstream JSONC settings snippet (no outer braces) and return
    (settings_dict, raw_block_with_comments_header).

    The block looks like:
      // updated YYYY-MM-DD HH:MM
      // https://github.com/antfu/vscode-file-nesting-config
      "explorer.fileNesting.enabled": true,
      ...
      "explorer.fileNesting.patterns": { ... },
    """
    # Extract the leading comment lines to preserve them in output
    comment_lines: list[str] = []
    for line in raw.splitlines():
        stripped = line.strip()
        if stripped.startswith("//"):
            comment_lines.append(line.rstrip())
        else:
            break
    header = "\n".join(comment_lines)

    # Wrap in braces so json5 can parse it
    parsed = json5.loads("{" + raw + "}")
    return parsed, header


def load_personal_config(path: Path) -> PersonalConfig:
    if not path.exists():
        console.print(f"[yellow]WARN[/yellow] {path} not found — no personal patterns applied.")
        return PersonalConfig()
    raw = yaml.safe_load(path.read_text())
    cfg = PersonalConfig.model_validate(raw or {})
    console.log(f"Loaded [bold]{len(cfg.patterns)}[/bold] personal pattern entries from {path}")
    return cfg


def merge_patterns(
    upstream_settings: dict,
    personal: PersonalConfig,
) -> dict[str, str]:
    """
    Merge personal patterns into the upstream explorer.fileNesting.patterns dict.
    - Personal entries OVERRIDE upstream entries with the same key.
    - New personal keys are APPENDED at the end.
    Returns the merged patterns dict.
    """
    patterns: dict[str, str] = dict(upstream_settings.get("explorer.fileNesting.patterns", {}))
    for entry in personal.patterns:
        value = ", ".join(entry.patterns)
        if entry.key in patterns:
            console.log(
                f"  [cyan]override[/cyan] {entry.key!r}: "
                f"{patterns[entry.key]!r} → {value!r}"
            )
        else:
            console.log(f"  [green]  append[/green] {entry.key!r}: {value!r}")
        patterns[entry.key] = value
    return patterns


def render_jsonc_block(
    upstream_settings: dict,
    merged_patterns: dict[str, str],
    header_comments: str,
) -> str:
    """Render the full VS Code settings snippet as JSONC."""
    enabled = upstream_settings.get("explorer.fileNesting.enabled", True)
    expand = upstream_settings.get("explorer.fileNesting.expand", False)

    pattern_lines = []
    items = list(merged_patterns.items())
    for i, (key, value) in enumerate(items):
        comma = "," if i < len(items) - 1 else ""
        pattern_lines.append(f'    {json5.dumps(key)}: {json5.dumps(value)}{comma}')

    lines = []
    if header_comments:
        lines.append(header_comments)
    lines.append(f'  "explorer.fileNesting.enabled": {json5.dumps(enabled)},')
    lines.append(f'  "explorer.fileNesting.expand": {json5.dumps(expand)},')
    lines.append('  "explorer.fileNesting.patterns": {')
    lines.extend(pattern_lines)
    lines.append("  }")
    return "\n".join(lines)


def render_readme(upstream_readme: str, merged_block: str) -> str:
    """Replace the jsonc block in the upstream README with the merged version."""
    new_fence = f"```jsonc\n{merged_block}\n```"
    result, n = JSONC_FENCE_PATTERN.subn(new_fence, upstream_readme, count=1)
    if n != 1:
        console.print("[red]ERROR[/red] Failed to splice merged jsonc back into README.")
        sys.exit(1)
    # Prepend our auto-gen note after the first heading line
    lines = result.splitlines(keepends=True)
    insert_at = next(
        (i + 1 for i, l in enumerate(lines) if l.startswith("#")), 0
    )
    lines.insert(insert_at, f"\n{REPO_NOTE}\n\n")
    return "".join(lines)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Merge personal file nesting patterns with upstream.")
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print merged README to stdout instead of writing README.md",
    )
    parser.add_argument(
        "--patterns",
        type=Path,
        default=Path("personal-patterns.yaml"),
        help="Path to personal-patterns.yaml (default: personal-patterns.yaml)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("README.md"),
        help="Output path for the rendered README.md (default: README.md)",
    )
    args = parser.parse_args()

    upstream_readme = fetch_upstream_readme()
    raw_jsonc = extract_jsonc_block(upstream_readme)
    upstream_settings, header_comments = parse_jsonc_block(raw_jsonc)
    upstream_patterns = upstream_settings.get("explorer.fileNesting.patterns", {})
    console.log(f"Upstream has [bold]{len(upstream_patterns)}[/bold] pattern entries")

    personal_cfg = load_personal_config(args.patterns)
    merged_patterns = merge_patterns(upstream_settings, personal_cfg)
    merged_block = render_jsonc_block(upstream_settings, merged_patterns, header_comments)
    final_readme = render_readme(upstream_readme, merged_block)

    if args.dry_run:
        console.print(Panel("[bold green]DRY RUN[/bold green] — writing to stdout"))
        sys.stdout.write(final_readme)
    else:
        args.output.write_text(final_readme, encoding="utf-8")
        console.print(
            Panel(
                f"[bold green]✓[/bold green] Written to [bold]{args.output}[/bold] "
                f"([cyan]{len(merged_patterns)}[/cyan] total patterns, "
                f"[green]+{len(personal_cfg.patterns)}[/green] personal)",
                title="merge_nesting.py",
            )
        )


if __name__ == "__main__":
    main()
